services:
  qdrant:
    image: qdrant/qdrant:v1.8.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/storage
    restart: unless-stopped
    networks:
      - app-network

  embedding-service:
    build: 
      context: app
      dockerfile: dockerfile
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - pip_cache:/root/.cache/pip
      - hf_cache:/root/.cache/huggingface
    depends_on:
      - qdrant
    environment:
      - EMBEDDING_MODEL=BAAI/bge-m3
      - QDRANT_URL=http://qdrant:6333
      - MD_DIR=knowledge_base
    restart: on-failure
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data:
  pip_cache:
  hf_cache: